### ISSUE TITLE
Auto tester does NOT fully detect Multi Thread errors.

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-sqe#418]
Auto tester needs to add a (or some) multi-thread test(s) to it's list.  

Currently the nightly runs are detecting one test failure on all multi-thread projects.

There are also two test failures on Multi Rank Projects, but this is not a concern because multi-rank is not included in the 6.0 release.

**Comment by allevin** [comment]
Upon discussing this with J. Vandyke, it was determined that the best solution is to add another (multithread) Jenkins project to the set of tests run for the auto-tester.  

However, since the current multithread tests are unstable (failing Cramsim, ember, and Scheduler), the autotester could randomly fail its tests.  It was decided to to wait to add the multithread tests to the autotester when these tests become stable.

**Comment by jpvandy** [comment]
A 2x2 test of memHierarchy sdl has been added to the autotester.

This provides significant multi thread/Rank coverage, but missed the core change that has some Merlin tests currently broken.
@allevin 
@nmhamster

**Comment by allevin** [comment]
This is an issue of coverage vs test-time and not an actual problem with the test system.

**Comment by berquist** [comment]
I suspect this isn't a problem anymore.
