### ISSUE TITLE
Red Hat builder is getting access errors on /dev/hfi1_0

### ISSUE THREAD

**Issue by jpvandy** [sstsimulator/sst-sqe#503]
Many test failures on the COE_RHEL builder

sst-coerhel7.sandia.gov.107064hfi_wait_for_device: The /dev/hfi1_0 device failed to appear after 15.0 seconds: Connection timed out.

The above line was appearing in the log of the failed tests.   The time out was not the failure that the test Suite was aborting.   The line was an extra line in the output file, which caused the Suite to abort the test because out did not match the gold file

@jwilso

**Comment by jpvandy** [comment]
Still failing today.  (Run start at 3:12 AM

**Comment by jwilso** [comment]
My guess is that something is broken in Red Hat’s OpenMPI.

Let me build an OpenMPI 1.10 from scratch.  I’ll let you know when it’s ready to try.  It should not require any changes to Bamboo or Jenkins.

J.

--
Jon Wilson
SST Software Engineering/Quality Assurance
CSRI
Sandia National Laboratories

**Comment by jpvandy** [comment]
The failure is gone in this AM's nightly as well as in all my efforts to create in other Jenkins test.   

I can't specify what change induced the error which persisted for 5 days or what was changed or fixed that made it go away.

If it doesn't recur before 7.0 this issue should be closed

**Comment by jwilso** [comment]
Ok,

Well, we tried the following things to try and pin down the cause of this issue.


1)       Reinstall the kernel

2)       Roll back to the previous kernel

3)       Reinstall OpenMPI (the Red Hat version)

4)       Roll back to the previous version of OpenMPI (the Red Hat version)

None of these improved the issue.  The only thing that does work is to use a manually-built version of OpenMPI 1.10.

There were some changes made on the 13th; the details as to who made the changes are not in the logfile, but I suspect that they were pushed in.  The COE RHEL installs are not like the other VMs; they differ in that they are visible to the network and are commandable by the COE so that they can push updates as needed for security and stability purposes.  While I try to be proactive and keep on top of the updates on a regular basis, there are occasionally updates that COE may push in order to secure certain vulnerabilities before I can apply them myself. Compounding this is that the change that has broken the bundled version may be Sandia-specific, and may not impact a standard RHEL7/CentOS 7 box. We do not have a standalone CentOS 7 builder that is configured to make use of the bundled OpenMPI; sst-test and sst-devel expressly do not have the OpenMPI RPM installed so that we can eliminate the possibility of users having conflicts with the versions we have in Modules.

Si, if you really think we need to be sure that the bundled OpenMPI is still usable on CentOS7/RHEL7, we can chase it down. I’ll have to build a CentOS 7 VM to do it (though I think I might have one laying around).

J.

--
Jon Wilson
SST Software Engineering/Quality Assurance
CSRI
Sandia National Laboratories

**Comment by jwilso** [comment]
Red Hat is aware of the problem.  It is logged as [bug 1408316](https://bugzilla.redhat.com/show_bug.cgi?id=1408316). Per comment number 10, a fix for this is not expected until release update 7.4.

As of 2017-FEB-07, Our CentOS 7 is at 7.3.1611.  As a workaround, use the manually built OpenMPI 1.10 for testing until the new release update to 7.4 is available.
